name: 'Deploy to Firebase Cloud Functions (Node 16)'
author: 'jsryudev <nsartor@mindthebridge.org>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions (Node 16)'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud-rain'
  color: 'blue'
